### PR TITLE
Fix backend status parsing

### LINKED ISSUE #2141: Fix backend status check

### PR DESCRIPTION
**Pull request by EricBAndrews**
## Issues

- closes #2141 

## Description

Adds logic to parse the richer healthcheck deployed in the last backend update.

If the healthcheck is bad, the readout now lists the health issues.

### CODE REVIEW

File: Mlem/App/Views/Root/Tabs/Settings/DeveloperSettingsView.swift [hunk 1]
```diff
@@ -94,13 +99,26 @@ struct DeveloperSettingsView: View {
         .navigationTitle("Developer")
     }
     
+    @ViewBuilder
+    private func backendStatusRow(good: Bool?) -> some View {
+        HStack {
+            Text(verbatim: "Status")
+            Spacer()
+            if let good {
+                Image(systemName: Icons.present).foregroundStyle(good ? .themedPositive : .themedNegative)
```
Comment (Sjmarf) [inline Mlem/App/Views/Root/Tabs/Settings/DeveloperSettingsView.swift]:
```suggestion
                Image(icon: .general.circle).foregroundStyle(good ? .themedPositive : .themedNegative)
                    .symbolVariant(.fill)
```

File: Mlem/App/Views/Root/Tabs/Settings/DeveloperSettingsView.swift [hunk 2]
```diff
@@ -94,13 +99,26 @@ struct DeveloperSettingsView: View {
         .navigationTitle("Developer")
     }
     
+    @ViewBuilder
+    private func backendStatusRow(good: Bool?) -> some View {
```
Comment (Sjmarf) [inline Mlem/App/Views/Root/Tabs/Settings/DeveloperSettingsView.swift]: *nit*

`good` might not be the best argument name here; maybe `isGood` or `isHealthy` would be better. Or alternatively using a 3-case enum rather than a `Bool?`

File: Mlem/Packages/MlemMiddleware/Sources/MlemMiddleware/Backend Client/BackendHealthCheck.swift [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+import Foundation
+
+public struct BackendHealthCheck: Decodable {
+    var dbConnection: Bool
+    var lastInstanceFetch: Date
+    
+    public var unhealthyReasons: [String] {
+        guard let minimumAllowableFetch = Calendar.current.date(byAdding: .day, value: -1, to: Date()) else {
+            assertionFailure("Could not compute minimum allowable fetch")
+            return .init(["Could not compute minimum allowable fetch"])
```
Comment (Sjmarf) [inline Mlem/Packages/MlemMiddleware/Sources/MlemMiddleware/Backend Client/BackendHealthCheck.swift]:
```suggestion
            return ["Could not compute minimum allowable fetch"]
```

**Review by Sjmarf — APPROVED** [review]
A few minor comments, otherwise LGTM 👍

File: Mlem/App/Views/Root/Tabs/Settings/DeveloperSettingsView.swift (hunk 2 above)
Comment (EricBAndrews) [reply Mlem/App/Views/Root/Tabs/Settings/DeveloperSettingsView.swift]: Updated to `isHealthy`.

I initially used a 3-case enum but it proved unwieldy--`Bool?` is more concise, and for a helper view in a dev settings page I don't expect the less descriptive API to be a problem down the line.

File: Mlem/App/Views/Root/Tabs/Settings/DeveloperSettingsView.swift [hunk 4]
```diff
@@ -94,13 +99,26 @@ struct DeveloperSettingsView: View {
         .navigationTitle("Developer")
     }
     
+    @ViewBuilder
+    private func backendStatusRow(isHealthy: Bool?) -> some View {
+        HStack {
+            Text(verbatim: "Status")
+            Spacer()
+            if let isHealthy {
+                Image(icon: .general.circle).foregroundStyle(isHealthy ? .themedPositive : .themedNegative)
```
Comment (Sjmarf) [inline Mlem/App/Views/Root/Tabs/Settings/DeveloperSettingsView.swift]: You'll need a `.symbolVariant` too I reckon (sorry, missed that in my first review)

Comment (EricBAndrews) [reply Mlem/App/Views/Root/Tabs/Settings/DeveloperSettingsView.swift]: Nice catch 😅
