### PR TITLE
Fix feed picker items appearing in ellipsis menu

### LINKED ISSUE #1937: Feed types appear in ellipsis menu at top of feed
https://github.com/user-attachments/assets/06a8cd18-a2b9-4be1-a5d8-df5956eb4eef

### PR DESCRIPTION
**Pull request by Sjmarf**
Closes #1937

### CODE REVIEW

File: Mlem/App/Views/Root/Tabs/Feeds/FeedsView.swift [hunk 1]
```diff
@@ -208,6 +195,61 @@ struct FeedsView: View {
...
+                            feedSelection: $feedSelection,
+                            scrollToTopTrigger: $scrollToTopTrigger
+                        )
+                    }
+                }
+            }
+            .isAtTopSubscriber(isAtTop: $isAtTop)
+            .onChange(of: isAtTop) {
+                print(isAtTop)
+            }
```
Comment (EricBAndrews) [inline Mlem/App/Views/Root/Tabs/Feeds/FeedsView.swift]: *nit*

Dead code?
```suggestion
```

**Review by EricBAndrews — APPROVED** [review]
Nice 👍
