### PR TITLE
Handle Multi-Word Keyword Filters

### LINKED ISSUE #1852: Multi-word keyword filters don't work
### Requirements

- [x] There are no existing issues for this bug report.

### Description

Following the filtering updates in 2.0, multi-word keyword filters (i.e., a filter with a space: `keyword filter`) no longer work.

### Mlem Version

_No response_

### PR DESCRIPTION
**Pull request by EricBAndrews**
## Issues

- closes #1852 

## Description

Improves the keyword filtering filtering algorithm to handle multi-word phrases. Phrases are matched on a word-by-word basis, so `multi phrase` is matched as `[multi, phrase]` against the split test string. This produces the following filter behavior:
- `title with multi phrase in it`: filtered
- `title with multi phrase's in it`: filtered
- `title with multi's phrase in it`: not filtered

## Implementation Notes

`FiltersTracker` is now responsible for parsing the raw user-provided keyword strings into a set of single word filters and multi-word phrase filters. Filters are still coded and stored as whole strings both to avoid coding compatibility problems and to make adding and removing keywords simpler.

### CODE REVIEW

File: Mlem/App/Globals/Definitions/FiltersTracker.swift [hunk 1]
```diff
@@ -76,12 +89,25 @@ class FiltersTracker {
...
     
     static var main: FiltersTracker = .init()
 }
 
+private func parseKeywordsAndPhrases(from rawKeywords: Set<String>) -> (keywords: Set<String>, phrases: Set<[String]>) {
+    var keywords: Set<String> = .init()
+    var phrases: Set<[String]> = .init()
+    for keyword in rawKeywords {
+        if keyword.contains(" ") {
+            phrases.insert(keyword.split(separator: " ").map { $0.lowercased() })
```
Comment (Sjmarf) [inline Mlem/App/Globals/Definitions/FiltersTracker.swift:103]: *nit*
```suggestion
            phrases.insert(keyword.split(separator: " ").map(\.lowercased))
```

**Review by Sjmarf — APPROVED** [review]
Nice, LGTM 💯
