### PR TITLE
PieFed: Fix post not marked read when voted on or saved

### LINKED ISSUE #2176: Post read state flickers when upvoting on PieFed

### PR DESCRIPTION
**Pull request by Sjmarf**
Closes #2176

### CODE REVIEW

File: Mlem/Packages/MlemMiddleware/Sources/MlemMiddleware/InstanceConnection/PiefedConnection/PieFedConnection+Post.swift [hunk 1]
```diff
@@ -161,15 +161,17 @@ public extension PieFedConnection {
...
-        return try .init(from: response.postView)
+        async let response = perform(request)
+        try await markPostAsRead(id: id, read: true)
+        return try await .init(from: response.postView, overrideRead: true)
     }
     
     @discardableResult
     func savePost(id: Int, save: Bool) async throws -> Post2Snapshot {
         let request = PieFedSavePostRequest(postId: id, save: save)
         let response = try await perform(request)
```
Comment (EricBAndrews) [inline Mlem/Packages/MlemMiddleware/Sources/MlemMiddleware/InstanceConnection/PiefedConnection/PieFedConnection+Post.swift]: Save uses `async let` for this--we should be consistent here

**Review by EricBAndrews — APPROVED** [review]
Nice! 👍 

One non-blocking nit

File: Mlem/Packages/MlemMiddleware/Sources/MlemMiddleware/InstanceConnection/PiefedConnection/PieFedConnection+Post.swift (hunk 1 above)
Comment (Sjmarf) [reply Mlem/Packages/MlemMiddleware/Sources/MlemMiddleware/InstanceConnection/PiefedConnection/PieFedConnection+Post.swift]: Nice catch, thanks 👍
