### PR TITLE
Fix search sheet on iOS 26

### LINKED ISSUE #2205: iOS 26: Search sheets missing search bar
This applies to the community search sheet inside of the post composer, the discussion language picker, etc. Anywhere where we use the custom `SearchBar` class inside of a sheet.

### PR DESCRIPTION
**Pull request by Sjmarf**
Closes #2205

### CODE REVIEW

File: Mlem/App/Views/Shared/Search/SearchBar/View+SheetSearchable.swift [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+                            .autocorrectionDisabled()
+                    }
+                    .padding(-10)
+                }
+            }
+    }
+}
+
+extension View {
+    func sheetSearchable(
```
Comment (EricBAndrews) [inline Mlem/App/Views/Shared/Search/SearchBar/View+SheetSearchable.swift]: *nit*

Something about the "-able" naming pattern for a view modifier feels a little off--I think `.withSearchSheet` might be a little more standard

**Review by EricBAndrews — APPROVED** [review]
LGTM! One note re: naming

File: Mlem/App/Views/Shared/Search/SearchBar/View+SheetSearchable.swift (hunk 1 above)
Comment (Sjmarf) [reply Mlem/App/Views/Shared/Search/SearchBar/View+SheetSearchable.swift]: I'm basing the name off the SwiftUI `.searchable` modifier here. I agree that it's a strange naming scheme. `.withSearchSheet` seems a little misleading to me - it implies that a new sheet is being added by the modifier, which isn't the case. The modifier just adds a search bar and cancel button to the view, and is only intended for use inside of a sheet. Maybe `.searchInsideSheet` or something? I'm not sure.

Comment (EricBAndrews) [reply Mlem/App/Views/Shared/Search/SearchBar/View+SheetSearchable.swift]: Fair point. I guess Apple does endorse "searchable," so I'd be fine keeping as is, though I still don't like that verbiage too much. The `.with...` pattern feels more natural for modifiers that add components to views--maybe `.withSheetSearch`?

Comment (Sjmarf) [reply Mlem/App/Views/Shared/Search/SearchBar/View+SheetSearchable.swift]: I'm happy with `.withSheetSearch` 👍
