### PR TITLE
iOS26 settings icons fix

### LINKED ISSUE #2213: "Settings icons" setting is ignored on iOS 26

### PR DESCRIPTION
**Pull request by EricBAndrews**
## Issues

- closes #2213 

## Description

Implements `ConditionalIconToggleStyle`, which forces toggles' labels to respect `a11y_showSettingsIcons`, and adds it to all views that use `.labelStyle(.conditional)`.

### CODE REVIEW

File: Mlem/App/Views/Root/Tabs/Settings/ZoomSliderSettingsView.swift [hunk 1]
```diff
@@ -69,6 +69,7 @@ struct ZoomSliderSettingsView: View {
             .pickerStyle(.inline)
         }
         .labelStyle(.conditional)
+        .toggleStyle(.conditional)
```
Comment (Sjmarf) [inline Mlem/App/Views/Root/Tabs/Settings/ZoomSliderSettingsView.swift]: We always use these two modifiers together. Maybe it's worth defining a `.withConditionalLabelStyle()` method on `View` that applies these? We could then define the `ConditionalLabelStyle` and `ConditionalToggleStyle` privately in the same file.

Comment (EricBAndrews) [reply Mlem/App/Views/Root/Tabs/Settings/ZoomSliderSettingsView.swift]: That is cleaner, implemented 👍

**Review by Sjmarf — APPROVED** [review]
LGTM 👍
