### PR TITLE
Fix toolbar on iOS 26

### LINKED ISSUE #2209: Toolbar bugs on iOS 26

### PR DESCRIPTION
**Pull request by Sjmarf**
Closes #2209

### CODE REVIEW

File: Mlem/App/Utility/Extensions/Views/View Modifiers/View+ButtonSizing.swift [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+        case .automatic: .automatic
+        case .flexible: .flexible
+        case .fitted: .fitted
+        }
+    }
+}
+
+extension View {
+    @ViewBuilder
+    func buttonSizing_(_ sizing: ButtonSizing_) -> some View {
```
Comment (EricBAndrews) [inline Mlem/App/Utility/Extensions/Views/View Modifiers/View+ButtonSizing.swift]:
```suggestion
    // TODO: iOS 18 deprecation remove this method
    func buttonSizing_(_ sizing: ButtonSizing_) -> some View {
```

File: Mlem/App/Views/Pages/Community/CommunityView.swift [hunk 2]
```diff
@@ -114,9 +114,16 @@ struct CommunityView: View {
             VStack {
                 switch selectedTab {
                 case .posts:
-                    if let postFeedLoader {
-                        postsTab(community: community, postFeedLoader: postFeedLoader)
-                            .padding(.bottom, -4)
+                    VStack {
```
Comment (EricBAndrews) [inline Mlem/App/Views/Pages/Community/CommunityView.swift:117]: *nit*
```suggestion
                    Group {
```

Unless there's some sneaky `VStack` behavior being used here

File: Mlem/App/Views/Pages/Community/FeedSortPicker.swift [hunk 3]
```diff
@@ -66,64 +104,91 @@ struct FeedSortPicker: View {
...
-            .presentationBackground(.clear)
-            .presentationCornerRadius(18)
-            .presentationCompactAdaptation(.popover)
-        }
+        .animation(.easeOut(duration: 0.4), value: value == .unknown)
+    }
+    
+    var isIos26: Bool {
+        if #available(iOS 26, *) { true } else { false }
     }
```
Comment (EricBAndrews) [inline Mlem/App/Views/Pages/Community/FeedSortPicker.swift]: We may wish to make this globally available--there are definitely other places we'll need a similar check

File: Mlem/App/Views/Root/Tabs/Inbox/InboxView+Views.swift [hunk 4]
```diff
@@ -117,57 +121,31 @@ extension InboxView {
     @ToolbarContentBuilder
     var toolbar: some ToolbarContent {
         ToolbarItem(placement: .topBarLeading) {
-            Button {
-                showRead.toggle()
-            } label: {
-                Label("Hide Read", icon: .general.filter)
-                    .symbolVariant(showRead ? .none : .fill)
+            if #available(iOS 26, *) {
```
Comment (EricBAndrews) [inline Mlem/App/Views/Root/Tabs/Inbox/InboxView+Views.swift]: See above re: globally available `isIos26`

File: Mlem/App/Views/Root/Tabs/Inbox/InboxView+Views.swift [hunk 5]
```diff
@@ -9,9 +9,13 @@ import MlemMiddleware
 import SwiftUI
 
 extension InboxView {
+    var shouldPinHeader: Bool {
+        if #available(iOS 26, *) { false } else { true }
+    }
```
Comment (EricBAndrews) [inline Mlem/App/Views/Root/Tabs/Inbox/InboxView+Views.swift]: See above re: globally available `isIos26`

File: Mlem/App/Views/Root/Tabs/Inbox/InboxView.swift [hunk 6]
```diff
@@ -173,6 +171,7 @@ struct InboxView: View {
                 .frame(width: 0, height: 0)
                 .onPreferenceChange(ScrollOffsetKey.self, perform: { value in
                     if value != headerPinned {
+                        if #available(iOS 26, *), headerPinned { return }
```
Comment (EricBAndrews) [inline Mlem/App/Views/Root/Tabs/Inbox/InboxView.swift]: See above re: globally available `isIos26`

File: Mlem/App/Views/Root/Tabs/Inbox/MarkAllAsReadButton.swift [hunk 7]
```diff
@@ -0,0 +1,78 @@
...
+                                }
+                                animationPlaying = false
+                            }
+                        } label: {
+                            if #available(iOS 26, *) {
+                                label(value: value)
+                            } else {
+                                label(value: value)
+                                    .background(.bar, in: .capsule)
+                            }
```
Comment (EricBAndrews) [inline Mlem/App/Views/Root/Tabs/Inbox/MarkAllAsReadButton.swift]: See above re: globally available `isIos26`

File: Mlem/App/Views/Root/Tabs/Inbox/MarkAllAsReadButton.swift [hunk 8]
```diff
@@ -0,0 +1,78 @@
...
+                        .opacity((newMessagesExist || value != 0) ? 1 : 0)
+                    }
+                }
+            }
+        }
+    }
+    
+    var shouldRemoveToolbarItem: Bool {
+        if #available(iOS 26, *) { true } else { false }
+    }
```
Comment (EricBAndrews) [inline Mlem/App/Views/Root/Tabs/Inbox/MarkAllAsReadButton.swift]: See above re: globally available `isIos26`

**Review by EricBAndrews — CHANGES_REQUESTED** [review]
Nice work!

File: Mlem/App/Utility/Extensions/Views/View Modifiers/View+ButtonSizing.swift (hunk 1 above)
Comment (Sjmarf) [reply Mlem/App/Utility/Extensions/Views/View Modifiers/View+ButtonSizing.swift]: Actually I didn't end up needing this extension after all; I'll remove it

File: Mlem/App/Views/Pages/Community/CommunityView.swift (hunk 2 above)
Comment (Sjmarf) [reply Mlem/App/Views/Pages/Community/CommunityView.swift:117]: `Group` has weird behavior with modifiers. The group itself can't have modifiers, so when you apply a modifier it applies it individually to each child view. This causes the modifier to only apply when the `postFeedLoader` is non-nil, so we need to use a "real" container view here.

File: Mlem/App/Views/Pages/Community/FeedSortPicker.swift (hunk 3 above)
Comment (Sjmarf) [reply Mlem/App/Views/Pages/Community/FeedSortPicker.swift]: Good idea 👍

File: Mlem/App/Views/Pages/Community/CommunityView.swift (hunk 2 above)
Comment (Sjmarf) [reply Mlem/App/Views/Pages/Community/CommunityView.swift:117]: I agree that `VStack` seems weird. Maybe `ZStack` is better? Or `AnyView` maybe. Or we could define our own bare-bones container view for this purpose.

Comment (Sjmarf) [reply Mlem/App/Views/Pages/Community/CommunityView.swift:117]: I agree that `VStack` seems weird. Maybe `ZStack` or `AnyView` would be better? Or we could define our own bare-bones container view for this purpose.

Comment (EricBAndrews) [reply Mlem/App/Views/Pages/Community/CommunityView.swift:117]: Gotcha. `VStack`, `ZStack`, and `AnyView` are basically equally janky IMO. A container would be neatest, but I'm fine merging with `VStack`.

**Review by EricBAndrews — APPROVED** [review]
LGTM! 🔥

File: Mlem/App/Views/Pages/Community/CommunityView.swift (hunk 2 above)
Comment (Sjmarf) [reply Mlem/App/Views/Pages/Community/CommunityView.swift:117]: I just tried defining a custom `SimpleContainer` type, but it produces the same output as the `Group` 🤔 Will stick with `VStack` for now.
