### PR TITLE
Preserve Image Filenames

### LINKED ISSUE #1477: Saving or sharing images in Mlem 2.0 doesn't use image's original file name
**Describe the bug**
Saving or sharing an image in the latest weekly build doesn't use the image's original file name, but just saves it as "image.jpeg". This might be true for the stable beta version as well, haven't checked.

This does still work in the latest v1 version of the app on the App Store.

**Expected Behavior**
Saving or sharing an image should use its original file name.

**Actual Behavior**
Images are shared or saved as "image.jpeg".

**To Reproduce**
1. Long tap on an image in a post to open the share menu
2. Choose share and save either to the Files app or a cloud storage provider
3. The image is saved as "image.jpeg"

**Mlem Information:**
Mlem 2.0 (154) (latest weekly build from TestFlight)

### PR DESCRIPTION
**Pull request by Sjmarf**
Closes #1477

### CODE REVIEW

File: Mlem/App/Logic/ImageFunctions.swift [hunk 1]
```diff
@@ -34,26 +34,28 @@ func fullSizeUrl(url: URL?) -> URL? {
...
            let baseUrl = URL(string: baseUrlString) {
-            fileType = baseUrl.pathExtension
+            fileName = baseUrl.lastPathComponent
+        } else {
+            fileName = url.lastPathComponent
         }
         
-        if fileType.isEmpty {
+        if fileName.isEmpty {
             assertionFailure("Empty fileType!")
```
Comment (EricBAndrews) [inline Mlem/App/Logic/ImageFunctions.swift]: *nit*

```suggestion
            assertionFailure("Empty fileName!")
```

**Review by EricBAndrews — APPROVED** [review]
LGTM! 🔥
