### PR TITLE
Fix crash when opening reply editor

### LINKED ISSUE #2007: Crash when opening reply editor
### Requirements

- [x] There are no existing issues for this bug report.

### Description

_No response_

### Mlem Version

_No response_

### PR DESCRIPTION
**Pull request by EricBAndrews**
## Issues

- closes #2007 

## Description

Fixes a crash when opening the reply editor. This was due to `person.crop` failing to resolve to a SFSymbol, which in turn crashed the force unwrap in `SimpleAvatarView:31`. This PR fixes the issue by updating `Icon.personAvatar` to `person.crop.circle` and adding a guard to prevent the force unwrap crashing the app, plus making it easier to debug. Also fixes `.select` not resolving.

### CODE REVIEW

File: Mlem/Packages/Icons/Sources/Icons/Icon+Lemmy.swift [hunk 1]
```diff
@@ -188,7 +188,7 @@ public extension Icon {
         
         @inlinable public var communityAvatar: Icon { community }
         public let instanceAvatar: Icon = .init("building.2.crop")
```
Comment (Sjmarf) [inline Mlem/Packages/Icons/Sources/Icons/Icon+Lemmy.swift]: We may want to apply the same logic here?

```suggestion
        public let instanceAvatar: Icon = .init("building.2.crop.circle")
```

**Review by Sjmarf — APPROVED** [review]
Nice 👍
