### PR TITLE
Fix "block" being shown for blocked communities rather than "unblock"

### LINKED ISSUE #2592: Make unblocking community more clear
If you already have a community blocked, clicking Block -> Community on a post unblocks it. However, it isn't very clear that this is what's happening:

https://github.com/user-attachments/assets/a1f3d051-2799-4f86-ac88-8e8031fda610

### PR DESCRIPTION
**Pull request by Sjmarf**
Previously, the popup would show "block community" and "block user" even when one was already blocked. Now, it shows "unblock community" / "unblock user" instead:

image

Closes #2592

### CODE REVIEW

File: Mlem/App/Actions/BlockAction.swift [hunk 1]
```diff
@@ -212,11 +212,21 @@ extension BlockAction {
...
+                contentType: item.blockable is Person ? .personOnly: .communityOnly
+            )
+            return .init(
+                title: label.title,
+                isDestructive: label.isDestructive,
+                callback: callback
+            )
         }
-        environment.popupModel?.showPopup(message: "Block...", actions)
+        environment.popupModel?.showPopup(message: "Community or user?", actions)
```
Comment (EricBAndrews) [inline Mlem/App/Actions/BlockAction.swift]: *nit*

This should match the order in which the options are presented:
```suggestion
        environment.popupModel?.showPopup(message: "User or community?", actions)
```

**Review by EricBAndrews — APPROVED** [review]
LGTM! 🔥
